/**
 * 주말 활동 데이터베이스
 *
 * 각 활동은 태그로 분류되어 사용자가 선택한 조건과 매칭됩니다.
 *  - region:     해당 활동이 가능한 지역 코드 배열
 *  - duration:   적합한 기간 코드 배열 (half | day | overnight)
 *  - theme:      활동의 테마 코드 배열
 *  - friendly:   충족하는 제한사항(긍정) 코드 배열
 *                (budget | kids | pet | transit | indoor | lowEnergy)
 *
 * 제한사항은 "이 조건을 만족하는가"로 필터링됩니다.
 * 예) 사용자가 'pet'(반려동물)을 선택하면 friendly에 'pet'이 있는 활동만 남습니다.
 */
window.ACTIVITIES = [
  {
    title: "한강공원 피크닉 & 자전거",
    desc: "돗자리 펴고 한강 바람 맞으며 휴식. 따릉이로 강변 라이딩까지.",
    region: ["seoul"],
    duration: ["half", "day"],
    theme: ["nature", "active"],
    friendly: ["budget", "kids", "pet", "transit", "lowEnergy"],
  },
  {
    title: "국립현대미술관 & 삼청동 산책",
    desc: "전시 관람 후 삼청동 골목 카페 투어. 비 와도 즐기기 좋아요.",
    region: ["seoul"],
    duration: ["half", "day"],
    theme: ["culture", "food"],
    friendly: ["transit", "indoor", "lowEnergy"],
  },
  {
    title: "성수동 카페거리 & 팝업 투어",
    desc: "감성 카페와 브랜드 팝업스토어가 모인 핫플레이스 도보 여행.",
    region: ["seoul"],
    duration: ["half", "day"],
    theme: ["food", "shopping", "culture"],
    friendly: ["transit", "indoor"],
  },
  {
    title: "북한산 둘레길 트레킹",
    desc: "도심에서 가까운 산. 가벼운 코스부터 정상까지 체력에 맞게 선택.",
    region: ["seoul", "gyeonggi"],
    duration: ["half", "day"],
    theme: ["nature", "active"],
    friendly: ["budget", "transit"],
  },
  {
    title: "에버랜드 / 롯데월드 나들이",
    desc: "온 가족이 즐기는 테마파크. 실내 어트랙션도 많아요.",
    region: ["gyeonggi", "seoul"],
    duration: ["day"],
    theme: ["active", "culture"],
    friendly: ["kids", "transit", "indoor"],
  },
  {
    title: "인천 차이나타운 & 월미도",
    desc: "이국적인 거리 먹거리와 바다 야경. 짜장면 발상지에서 한 끼.",
    region: ["gyeonggi"],
    duration: ["half", "day"],
    theme: ["food", "culture"],
    friendly: ["budget", "kids", "transit"],
  },
  {
    title: "남이섬 & 가평 레일바이크",
    desc: "강을 따라 페달을 밟는 레일바이크와 메타세쿼이아 숲길 산책.",
    region: ["gangwon", "gyeonggi"],
    duration: ["day", "overnight"],
    theme: ["nature", "active"],
    friendly: ["kids", "pet"],
  },
  {
    title: "강릉 안목해변 카페거리 & 정동진",
    desc: "바다 보며 커피 한 잔, 정동진 일출 명소까지. 1박이면 더 여유롭게.",
    region: ["gangwon"],
    duration: ["day", "overnight"],
    theme: ["nature", "food", "healing"],
    friendly: ["pet", "lowEnergy"],
  },
  {
    title: "평창·홍천 온천 & 휴양림",
    desc: "숲속 휴양림에서 산책하고 온천으로 피로 풀기. 완전한 휴식 코스.",
    region: ["gangwon"],
    duration: ["overnight"],
    theme: ["healing", "nature"],
    friendly: ["lowEnergy", "indoor"],
  },
  {
    title: "속초 설악산 케이블카 & 대포항",
    desc: "케이블카로 편하게 즐기는 설악산 절경, 대포항 회센터에서 저녁.",
    region: ["gangwon"],
    duration: ["day", "overnight"],
    theme: ["nature", "food"],
    friendly: ["kids", "lowEnergy"],
  },
  {
    title: "공주·부여 백제 역사 유적지",
    desc: "유네스코 세계유산을 걷는 역사 여행. 무령왕릉과 부소산성 코스.",
    region: ["chungcheong"],
    duration: ["day", "overnight"],
    theme: ["culture", "nature"],
    friendly: ["budget", "kids"],
  },
  {
    title: "대전 성심당 & 한밭수목원",
    desc: "전국구 빵지순례 성지에서 빵 한 보따리, 도심 수목원에서 소화 산책.",
    region: ["chungcheong"],
    duration: ["half", "day"],
    theme: ["food", "nature"],
    friendly: ["budget", "kids", "transit", "lowEnergy"],
  },
  {
    title: "전주 한옥마을 & 비빔밥 투어",
    desc: "한복 입고 한옥 골목 산책, 전주 한정식과 비빔밥으로 미식 여행.",
    region: ["jeolla"],
    duration: ["day", "overnight"],
    theme: ["culture", "food"],
    friendly: ["kids", "transit"],
  },
  {
    title: "여수 밤바다 & 케이블카",
    desc: "낭만 포차거리와 해상 케이블카 야경. 1박으로 오동도까지 둘러보기.",
    region: ["jeolla"],
    duration: ["overnight"],
    theme: ["nature", "food", "healing"],
    friendly: ["lowEnergy"],
  },
  {
    title: "순천만 국가정원 & 습지 산책",
    desc: "드넓은 갈대밭과 정원을 거니는 힐링 코스. 사진 명소가 가득.",
    region: ["jeolla"],
    duration: ["day", "overnight"],
    theme: ["nature", "healing"],
    friendly: ["kids", "pet", "lowEnergy"],
  },
  {
    title: "경주 불국사 & 보문단지 라이딩",
    desc: "천년 고도 역사 탐방과 보문호수 자전거. 첨성대 야경은 덤.",
    region: ["gyeongsang"],
    duration: ["day", "overnight"],
    theme: ["culture", "active", "nature"],
    friendly: ["budget", "kids"],
  },
  {
    title: "안동 하회마을 & 찜닭거리",
    desc: "전통 마을에서 느긋한 산책 후 안동찜닭으로 든든하게.",
    region: ["gyeongsang"],
    duration: ["day", "overnight"],
    theme: ["culture", "food"],
    friendly: ["budget", "kids", "lowEnergy"],
  },
  {
    title: "통영 케이블카 & 동피랑 벽화마을",
    desc: "한려수도 절경 케이블카와 알록달록 벽화 골목, 충무김밥 한 끼.",
    region: ["gyeongsang"],
    duration: ["day", "overnight"],
    theme: ["nature", "culture", "food"],
    friendly: ["kids", "lowEnergy"],
  },
  {
    title: "부산 해운대 & 광안리 해변",
    desc: "해변 산책과 더베이101 야경, 광안대교를 배경으로 한 분위기.",
    region: ["busan"],
    duration: ["half", "day", "overnight"],
    theme: ["nature", "food", "healing"],
    friendly: ["pet", "transit", "lowEnergy"],
  },
  {
    title: "부산 감천문화마을 & 자갈치시장",
    desc: "사진 명소 컬러풀 마을 골목과 활기찬 수산시장 먹거리 탐방.",
    region: ["busan"],
    duration: ["half", "day"],
    theme: ["culture", "food"],
    friendly: ["budget", "kids", "transit"],
  },
  {
    title: "제주 올레길 트레킹",
    desc: "해안과 오름을 잇는 올레길. 코스별 난이도 선택으로 누구나 OK.",
    region: ["jeju"],
    duration: ["day", "overnight"],
    theme: ["nature", "active", "healing"],
    friendly: ["budget", "pet"],
  },
  {
    title: "제주 동쪽 카페 & 비자림",
    desc: "성산일출봉 뷰 카페와 신비로운 비자림 숲길. 느긋한 드라이브 코스.",
    region: ["jeju"],
    duration: ["day", "overnight"],
    theme: ["nature", "food", "healing"],
    friendly: ["pet", "lowEnergy"],
  },
  {
    title: "제주 아쿠아플라넷 & 실내 테마관",
    desc: "비 오는 날에도 끄떡없는 대형 아쿠아리움과 실내 전시. 아이들 인기 만점.",
    region: ["jeju"],
    duration: ["half", "day"],
    theme: ["culture", "active"],
    friendly: ["kids", "indoor", "lowEnergy"],
  },
  {
    title: "동네 방탈출 & 보드게임 카페",
    desc: "날씨 상관없이 실내에서 머리 쓰며 노는 코스. 친구·연인 모두 환영.",
    region: ["seoul", "gyeonggi", "busan", "gyeongsang", "chungcheong", "jeolla", "gangwon", "jeju"],
    duration: ["half"],
    theme: ["active", "culture"],
    friendly: ["budget", "transit", "indoor", "lowEnergy"],
  },
  {
    title: "원데이 클래스 (도자기·향수·베이킹)",
    desc: "손으로 만드는 나만의 작품. 실내에서 부담 없이 즐기는 취미 체험.",
    region: ["seoul", "gyeonggi", "busan", "gyeongsang", "chungcheong", "jeolla", "gangwon", "jeju"],
    duration: ["half", "day"],
    theme: ["culture", "shopping"],
    friendly: ["transit", "indoor", "lowEnergy"],
  },
  {
    title: "대형 쇼핑몰 & 영화관 데이",
    desc: "쇼핑, 맛집, 영화까지 한 건물에서 해결. 더위·추위·비 걱정 없음.",
    region: ["seoul", "gyeonggi", "busan", "gyeongsang", "chungcheong", "jeolla"],
    duration: ["half", "day"],
    theme: ["shopping", "food", "culture"],
    friendly: ["kids", "transit", "indoor", "lowEnergy"],
  },
];
